config/routes.rb
Precipice::Application.routes.draw do
  
  resources :print_types

  resources :discount_codes

  get "errors/error_404"
  get "errors/error_500"
  resources :site_photos

  resources :additional_contents

  resources :customer_orders
  
  
  get 'shopping_cart', to: 'shopping_carts#show'
  post 'update_shopping_cart', to: 'shopping_carts#update'
  resources :shopping_carts, only: [:index, :destroy]
  
  get 'order_complete', to: 'customer_orders#complete', as: :order_complete
  get 'charge_error', to: 'customer_orders#charge_error', as: :charge_error
  get 'checkout', to: 'customer_orders#new', as: :checkout
  get 'order_error', to: 'customer_orders#order_error', as: :order_error

  resources :print_options do
    collection do
      put 'update_order'
    end
  end

  devise_for :admins, :controllers => {:registrations => "registrations"}
  
  
  resources :galleries do
    member do
      get "manage"
    end
  end
  
  resources :collections do
    collection do
      get "edit_display_order"
      put "update_display_order"
    end
  end

  resources :photos do
    collection do
      get "uncategorized"
      get "manage_slideshow"
      put "update_slideshow"
    end
    member do
      get "show_full_size"
    end
  end
  
   
   get '404', :to => 'application#page_not_found'
   get '422', :to => 'application#server_error'
   get '500', :to => 'application#server_error'
  

  

  

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  extend FriendlyId
  friendly_id :name, use: :slugged
   
  has_many :galleries, :inverse_of => :collection, :dependent => :restrict_with_error
  
  validates_presence_of :name 

  default_scope {order(:display_order)}
  
  ### Nested attributes
  accepts_nested_attributes_for :galleries #, reject_if: proc { |attributes| attributes['name'].blank? }
  
  def should_generate_new_friendly_id?
    name_changed? || slug.nil?
  end
  
  
  
end

app/controllers/collections_controller.rb
class CollectionsController < ApplicationController
  before_action :set_collection, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_admin!, only: [:index, :new, :edit, :create, :update, :destroy]
  
  # GET /collections
  # GET /collections.json
  def index
    @collections = Collection.all
  end

  # GET /collections/1
  # GET /collections/1.json
  def show
    if @collection.galleries.count == 1
      redirect_to @collection.galleries.first
    end
  end

  # GET /collections/new
  def new
    @collection = Collection.new
  end

  # GET /collections/1/edit
  def edit
  end

  # POST /collections
  # POST /collections.json
  def create
    @collection = Collection.new(collection_params)

    respond_to do |format|
      if @collection.save
        format.html { redirect_to collections_url, notice: 'Collection was successfully created.' }
        format.json { render action: 'show', status: :created, location: @collection }
      else
        format.html { render action: 'new' }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /collections/1
  # PATCH/PUT /collections/1.json
  def update
    respond_to do |format|
      if @collection.update(collection_params)
        format.html { redirect_to collections_url, notice: 'Collection was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @collection.errors, status: :unprocessable_entity }
      end
    end
  end
  
  def edit_display_order
    @collections = Collection.all
  end
  
  def update_display_order
     params[:collections].values.each do |collection_values|
        Collection.update(collection_values['id'], display_order: collection_values['display_order']) 
     end 
     
     redirect_to collections_path
  end

  # DELETE /collections/1
  # DELETE /collections/1.json
  def destroy
    @collection.destroy
    respond_to do |format|
      format.html { redirect_to collections_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_collection
      @collection = Collection.friendly.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def collection_params
      params.require(:collection).permit(:name, :for_sale_flag, galleries_attributes: [:id, :name,:order_in_collection])
    end
end

app/helpers/collections_helper.rb
module CollectionsHelper
end

app/views/collections/_form.html.erb
<div class="row">
	<div class="col-md-6 col-md-offset-1">
		<%= form_for(@collection,html:{role:"form", class:"form-horizontal"}) do |f| %>
		  <% if @collection.errors.any? %>
		    <div id="error_explanation">
		      <h2><%= pluralize(@collection.errors.count, "error") %> prohibited this collection from being saved:</h2>
		
		      <ul>
		      <% @collection.errors.full_messages.each do |msg| %>
		        <li><%= msg %></li>
		      <% end %>
		      </ul>
		    </div>
		  <% end %>
		
		  <div class="form-group">
		    <%= f.label :name %><br>
		    <%= f.text_field :name, class: "form-control" %>
		  </div>
		  
		  <div class="checkbox-inline">
		    
		    	<%= f.check_box :for_sale_flag %>
		    	<%= f.label :for_sale_flag, "Allow photos in this collection to be listed for selling." %>
		    
		    
		  </div>
		  
		  <h3 class="top-buffer-big">Manage Gallery Order</h3>
		  <p>
		  	Drag and drop the gallery names into the preferred order.<br>
		  	Be sure to press the "submit" button when you're done.
		  </p>
		  <div class="form-group">
			<ul class="list-group sortable">
	  			<% @collection.galleries.collection_order.each do |gallery|%>
		  			<li class="list-group-item  handle">
			  			<%= f.fields_for :galleries, gallery do |galleries_form|%>	
			  				<%= gallery.name%>
			  				<%= galleries_form.hidden_field :order_in_collection, data: {content: "sort_order_field"}%>
			  			<%end%>
		  			</li>
	  			<%end%>
	  		</ul>  	
		  </div>
		  
		  <div class="form-group top-buffer-big">
		   <button type="submit" class="btn btn-default">Submit</button>
		  </div>
		<% end %>	
	</div>
</div>

app/views/collections/edit.html.erb
<div class="row top-buffer-big">
	<div class="col-md-12">
		<div class="well">
			<h3>Edit <%= @collection.name %> collection</h3>
		
	
	
			<%= render 'form' %>
	
	
			<div class="row top-buffer-big">
				<div class="col-md-12">
					<%= link_to 'View Collection', @collection %> |
					<%= link_to 'Manage Photos', collections_path %>
				</div>
			</div>
		</div>
	</div>
</div>

app/views/collections/edit_display_order.html.erb
<div class="row">
	<div class="col-md-5">
		<%= form_tag update_display_order_collections_path,  method: :put  do %>
			<% @collections.each do |collection| %>
			
			
			
			
			<%end%>
			
			<ul class="list-group sortable">
	  			<% @collections.each do |collection| %>
		  			<li class="list-group-item  handle">
			  			<%= collection.name %>
			  			
			  			<%= fields_for "collections[]", collection do |collection_form| %>
							<%= collection_form.hidden_field :id %>
							<%= collection_form.hidden_field :display_order, data:{content: "sort_order_field"} %>
						<%end%>
		  			</li>
	  			<%end%>
	  		</ul>  	
			
			<button type="submit" class="btn btn-default">Submit</button>
		<%end%>
	</div>
</div>

app/views/collections/index.html.erb
<div class="container">
	<div class="row clearfix">
		<div class="col-md-12 column">
			<h3 class="text-default">
				Photo Collections - 
				<small class="horz-padding">
					<%= link_to "Manage Collection Order", edit_display_order_collections_path %>
				</small>
			</h3>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-3 column">
	 		<div class="list-group">
			 	<%= link_to "Create a new Collection", new_collection_path, class:"list-group-item" %>
			</div>
		</div>
	 </div>
		
	
	<% Collection.all.each do |collection| %>
		<div class="row">
			<div class="col-md-11  column">
				<div class="panel panel-default">
				  	<div class="panel-heading">
				  		<strong><%= link_to collection.name, collection %></strong>
				  		- <%= link_to 'edit', edit_collection_path(collection), class: "text-muted" %>
				  		- <%= link_to 'delete', collection, method: :delete, data: { confirm: 'Are you sure?' }, class: "text-muted" %>
				  	</div>
					
					<div class="panel-body">
				    	<!-- List group -->
						<div class="list-group">
							<% collection.galleries.collection_order.each do |gallery|%>		
								<%= link_to(manage_gallery_path(gallery), {:class => "list-group-item"}) do %>
									<%= gallery.name%>
									<div class="row">
										<div class="col-md-10 col-md-offset-1">
											<% gallery.photos.use_gallery_order.each do |photo|%>
												<%= image_tag photo.photo_file.url(:thumb), class: "img-thumbnail" %>
											<%end%>
											
											
											<%if gallery.photos.blank?%>
												<span class="text-muted">No photos have been uploaded to this gallery</span>
											<%end%>
										</div>
									</div>
								<%end%>							
							<%end%>
						</div>
						
						<div class="row">
							<div class="col-md-11">
								<%= form_for(collection, html:{role: "form", class: "form-horizontal"}) do |f| %>
									<%=f.fields_for :galleries, collection.galleries.new do |gallery_form| %>
										<div class="form-group">
											<%= gallery_form.label :name, class: "hidden" %>
											<div class="col-md-3">
												<%= gallery_form.text_field :name, :class => 'form-control input-sm' %>	
											</div>
											<div class="7">
												<button type="submit" class="btn btn-default btn-sm">Create a new Gallery</button>
											</div>
										</div>
									<%end%>
								<%end%>		
							</div>	
						</div>
						
					</div>
				</div>	  	
			</div>
		</div>
	<%end%>
	
	<div class="row">
		<div class="col-md-11  column">
			<div class="panel panel-default">
			  	<div class="panel-heading">
			  		<strong>Uncatgorized Photos</strong>
			  	</div>
				
				<div class="panel-body">
			    	<!-- List group -->
					<div class="list-group">
							<%= link_to(uncategorized_photos_path, {:class => "list-group-item"}) do %>
								<div class="row">
									<div class="col-md-10 col-md-offset-1">
										<% Photo.uncategorized.each do |photo|%>
											<%= image_tag photo.photo_file.url(:thumb), class: "img-thumbnail" %>
										<%end%>
									</div>
								</div>
							<%end%>							
					</div>
				</div>
			</div>
		</div>
	</div>	
</div>

app/views/collections/new.html.erb
<h1>New collection</h1>

<%= render 'form' %>

<%= link_to 'Back', collections_path %>

app/views/collections/show.html.erb
<div class="row">
	<div class="col-sm-12">
		<div class="top-buffer">
			<div class="well well-sm well-transparent text-center">
				<span class="lead classy-text punched-text">
						<%= @collection.name%> Galleries
				</span>		
			</div>	
		</div>
	</div>
</div>

<% @collection.galleries.collection_order.each do |gallery| %>
	<div class="row top-buffer-big">
		<div class="col-md-12 col-sm-12">
			<span class="lead classy-text punched-text">
				<%= gallery.name%>
			</span>
			- 
			<%= link_to gallery, { class: "text-info"} do %>
				 <% if gallery.photos.count > 6 %>
				 	see all <%= gallery.photos.count %> photos in gallery
				 <%else%>
				 	go to gallery
				 <%end%>
			<%end%>
		</div>
		<div class="col-xs-12 top-buffer">
			<span class="horz-padding">
				<%= gallery.description %>
			</span>
		</div>
	</div>
	
	<% gallery.photos.use_gallery_order.limit(6).in_groups_of(3, false).each do |photo_group|%>
	<div class="row"  data-content="thumbnail-row">
		<% photo_group.each do |photo|%>
			<div class="col-md-4 top-buffer col-sm-6">
				<%= link_to photo,{title: photo.name} do %>
					<%= image_tag photo.photo_file.url(:medium), class: "img-rounded photo-border"%> 
				<%end%>
			</div>		
		<%end%>
	</div>
	<%end%>
<%end%>