config/routes.rb
Precipice::Application.routes.draw do
  
  resources :print_types

  resources :discount_codes

  get "errors/error_404"
  get "errors/error_500"
  resources :site_photos

  resources :additional_contents

  resources :customer_orders
  
  
  get 'shopping_cart', to: 'shopping_carts#show'
  post 'update_shopping_cart', to: 'shopping_carts#update'
  resources :shopping_carts, only: [:index, :destroy]
  
  get 'order_complete', to: 'customer_orders#complete', as: :order_complete
  get 'charge_error', to: 'customer_orders#charge_error', as: :charge_error
  get 'checkout', to: 'customer_orders#new', as: :checkout
  get 'order_error', to: 'customer_orders#order_error', as: :order_error

  resources :print_options do
    collection do
      put 'update_order'
    end
  end

  devise_for :admins, :controllers => {:registrations => "registrations"}
  
  
  resources :galleries do
    member do
      get "manage"
    end
  end
  
  resources :collections do
    collection do
      get "edit_display_order"
      put "update_display_order"
    end
  end

  resources :photos do
    collection do
      get "uncategorized"
      get "manage_slideshow"
      put "update_slideshow"
    end
    member do
      get "show_full_size"
    end
  end
  
   
   get '404', :to => 'application#page_not_found'
   get '422', :to => 'application#server_error'
   get '500', :to => 'application#server_error'
  

  

  

end

app/models/discount_code.rb
class DiscountCode < ActiveRecord::Base
  validates_presence_of :name, :discount_percentage
  
  validates_numericality_of :discount_percentage, :greater_than => 0, :less_than => 100, :only_integer => true

  before_save :downcase_name
  
  def downcase_name
    self.name = self.name.downcase
  end

end

app/controllers/discount_codes_controller.rb
class DiscountCodesController < ApplicationController
  before_action :set_discount_code, only: [:show, :edit, :update, :destroy]

  # GET /discount_codes
  # GET /discount_codes.json
  def index
    @discount_codes = DiscountCode.all
  end

  # GET /discount_codes/1
  # GET /discount_codes/1.json
  def show
  end

  # GET /discount_codes/new
  def new
    @discount_code = DiscountCode.new
  end

  # GET /discount_codes/1/edit
  def edit
  end

  # POST /discount_codes
  # POST /discount_codes.json
  def create
    @discount_code = DiscountCode.new(discount_code_params)

    respond_to do |format|
      if @discount_code.save
        format.html { redirect_to @discount_code, notice: 'Discount code was successfully created.' }
        format.json { render action: 'show', status: :created, location: @discount_code }
      else
        format.html { render action: 'new' }
        format.json { render json: @discount_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /discount_codes/1
  # PATCH/PUT /discount_codes/1.json
  def update
    respond_to do |format|
      if @discount_code.update(discount_code_params)
        format.html { redirect_to @discount_code, notice: 'Discount code was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @discount_code.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /discount_codes/1
  # DELETE /discount_codes/1.json
  def destroy
    @discount_code.destroy
    respond_to do |format|
      format.html { redirect_to discount_codes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_discount_code
      @discount_code = DiscountCode.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def discount_code_params
      params.require(:discount_code).permit(:name, :discount_percentage)
    end
end

app/helpers/discount_codes_helper.rb
module DiscountCodesHelper
end

app/views/discount_codes/_form.html.erb
<div class="col-md-6">
	<%= form_for(@discount_code, role: "form") do |f| %>
	  <% if @discount_code.errors.any? %>
	    <div id="error_explanation">
	      <h2><%= pluralize(@discount_code.errors.count, "error") %> prohibited this discount_code from being saved:</h2>
	
	      <ul>
	      <% @discount_code.errors.full_messages.each do |msg| %>
	        <li><%= msg %></li>
	      <% end %>
	      </ul>
	    </div>
	  <% end %>
	
		<div class="form-group">
	    	<%= f.label :name, "Discount Code" %>
	    	<div>
	    		Use lowercase letters (uppercase will be converted to lowercase)
	    	</div>
	    	<%= f.text_field :name , class: "form-control"%>
	  	</div>
	  	<div class="form-group">
	    	<%= f.label :discount_percentage, "Percent Off" %>
	    	<div>
	    		Use an integer between 1 and 99.
	    	</div>
	    	<%= f.number_field :discount_percentage, class:"form-control" %>
	  	</div>
	  	<div class="actions">
	    	<button class="btn btn-default" type="submit">Save</button>
	  	</div>
	<% end %>
	
	
</div>

app/views/discount_codes/edit.html.erb
<%= render 'form' %>

<div class="col-md-12 top-buffer-big">
	<%= link_to 'Cancel', discount_codes_path %>
</div>

app/views/discount_codes/index.html.erb
<div class="col-md-6">

	<h3>Discount Codes</h3>
	
	<table class="table">
	  <thead>
	    <tr>
	      <th>Name</th>
	      <th>Percent Off</th>
	      <th></th>
	      <th></th>
	    </tr>
	  </thead>
	
	  <tbody>
	    <% @discount_codes.each do |discount_code| %>
	      <tr>
	        <td><%= discount_code.name %></td>
	        <td><%= discount_code.discount_percentage %>%</td>
	        <td><%= link_to 'Edit', edit_discount_code_path(discount_code) %></td>
	        <td><%= link_to 'Delete', discount_code, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	      </tr>
	    <% end %>
	  </tbody>
	</table>
	
	<br>
	
	<%= link_to 'New Discount code', new_discount_code_path %>
</div>

app/views/discount_codes/new.html.erb
<div class="col-md-12">
	<h3>Create Discount Code</h3>	
</div>

<%= render 'form' %>

<div class="col-md-12 top-buffer-big">
	<%= link_to 'Cancel', discount_codes_path %>
</div>

app/views/discount_codes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @discount_code.name %>
</p>

<p>
  <strong>Discount percentage:</strong>
  <%= @discount_code.discount_percentage %>
</p>

<%= link_to 'Edit', edit_discount_code_path(@discount_code) %> |
<%= link_to 'Back', discount_codes_path %>