config/routes.rb
Precipice::Application.routes.draw do
  
  resources :print_types

  resources :discount_codes

  get "errors/error_404"
  get "errors/error_500"
  resources :site_photos

  resources :additional_contents

  resources :customer_orders
  
  
  get 'shopping_cart', to: 'shopping_carts#show'
  post 'update_shopping_cart', to: 'shopping_carts#update'
  resources :shopping_carts, only: [:index, :destroy]
  
  get 'order_complete', to: 'customer_orders#complete', as: :order_complete
  get 'charge_error', to: 'customer_orders#charge_error', as: :charge_error
  get 'checkout', to: 'customer_orders#new', as: :checkout
  get 'order_error', to: 'customer_orders#order_error', as: :order_error

  resources :print_options do
    collection do
      put 'update_order'
    end
  end

  devise_for :admins, :controllers => {:registrations => "registrations"}
  
  
  resources :galleries do
    member do
      get "manage"
    end
  end
  
  resources :collections do
    collection do
      get "edit_display_order"
      put "update_display_order"
    end
  end

  resources :photos do
    collection do
      get "uncategorized"
      get "manage_slideshow"
      put "update_slideshow"
    end
    member do
      get "show_full_size"
    end
  end
  
   
   get '404', :to => 'application#page_not_found'
   get '422', :to => 'application#server_error'
   get '500', :to => 'application#server_error'
  

  

  

end

app/models/site_photo.rb
class SitePhoto < ActiveRecord::Base
   has_attached_file :photo_file, :styles => { :medium => "250x250>", 
                                               :thumb => "100x100>", 
                                               :large => "900x900>",
                                               :original => "1400x1400>" },
                                               :convert_options => {:thumb => "-quality 60 -strip",
                                                                    :medium => "-quality 60 -strip",
                                                                    :large => "-quality 60 -strip",
                                                                    :original => "-quality 75" }, 
                                               :default_url => "/images/:style/missing.png"
   
  validates_attachment_content_type :photo_file, :content_type => %w(image/jpeg image/jpg image/png)
  



end

app/controllers/site_photos_controller.rb
class SitePhotosController < ApplicationController
  before_action :set_site_photo, only: [:show, :edit, :update, :destroy]

  # GET /site_photos
  # GET /site_photos.json
  def index
    @site_photos = SitePhoto.all
  end

  # GET /site_photos/1
  # GET /site_photos/1.json
  def show
  end

  # GET /site_photos/new
  def new
    @site_photo = SitePhoto.new
  end

  # GET /site_photos/1/edit
  def edit
  end

  # POST /site_photos
  # POST /site_photos.json
  def create
    @site_photo = SitePhoto.new(site_photo_params)

    respond_to do |format|
      if @site_photo.save
        format.html { redirect_to @site_photo, notice: 'Site photo was successfully created.' }
        format.json { render action: 'show', status: :created, location: @site_photo }
      else
        format.html { render action: 'new' }
        format.json { render json: @site_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /site_photos/1
  # PATCH/PUT /site_photos/1.json
  def update
    respond_to do |format|
      if @site_photo.update(site_photo_params)
        format.html { redirect_to @site_photo, notice: 'Site photo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @site_photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /site_photos/1
  # DELETE /site_photos/1.json
  def destroy
    @site_photo.destroy
    respond_to do |format|
      format.html { redirect_to site_photos_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_site_photo
      @site_photo = SitePhoto.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def site_photo_params
      params.require(:site_photo).permit(:name, :photo_file)
    end
end

app/helpers/site_photos_helper.rb
module SitePhotosHelper
end

app/views/site_photos/_form.html.erb
<%= form_for(@site_photo) do |f| %>
  <% if @site_photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@site_photo.errors.count, "error") %> prohibited this site_photo from being saved:</h2>

      <ul>
      <% @site_photo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

	<div class="form-group">
		 Upload Photo:
		 <%= f.file_field :photo_file %>
	</div>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/site_photos/edit.html.erb
<h1>Editing site_photo</h1>

<%= render 'form' %>

<%= link_to 'Show', @site_photo %> |
<%= link_to 'Back', site_photos_path %>

app/views/site_photos/index.html.erb
<h3>Site photos</h3>

<table class="table-condensed">
  <thead>
    <tr>
    	<th>Photo</th>
      <th>Name</th>
      <th>URL (900px on the long edge)</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @site_photos.each do |site_photo| %>
      <tr>
        <td><%= image_tag site_photo.photo_file.url(:thumb)%></td>
        <td><%= site_photo.name %></td>
        <td> <%= site_photo.photo_file.url(:large)%> </td>
        <td><%= link_to 'Show', site_photo %></td>
        <td><%= link_to 'Edit', edit_site_photo_path(site_photo) %></td>
        <td><%= link_to 'Destroy', site_photo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Site photo', new_site_photo_path %>

app/views/site_photos/new.html.erb
<h1>New site_photo</h1>

<%= render 'form' %>

<%= link_to 'Back', site_photos_path %>

app/views/site_photos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @site_photo.name %>
  <div>
  	<%= image_tag @site_photo.photo_file.url(:large)%>	
  </div>
  
</p>

<%= link_to 'Edit', edit_site_photo_path(@site_photo) %> |
<%= link_to 'Back', site_photos_path %> |
<%= link_to "New Site Photo", new_site_photo_path%>