config/routes.rb
Precipice::Application.routes.draw do
  
  resources :print_types

  resources :discount_codes

  get "errors/error_404"
  get "errors/error_500"
  resources :site_photos

  resources :additional_contents

  resources :customer_orders
  
  
  get 'shopping_cart', to: 'shopping_carts#show'
  post 'update_shopping_cart', to: 'shopping_carts#update'
  resources :shopping_carts, only: [:index, :destroy]
  
  get 'order_complete', to: 'customer_orders#complete', as: :order_complete
  get 'charge_error', to: 'customer_orders#charge_error', as: :charge_error
  get 'checkout', to: 'customer_orders#new', as: :checkout
  get 'order_error', to: 'customer_orders#order_error', as: :order_error

  resources :print_options do
    collection do
      put 'update_order'
    end
  end

  devise_for :admins, :controllers => {:registrations => "registrations"}
  
  
  resources :galleries do
    member do
      get "manage"
    end
  end
  
  resources :collections do
    collection do
      get "edit_display_order"
      put "update_display_order"
    end
  end

  resources :photos do
    collection do
      get "uncategorized"
      get "manage_slideshow"
      put "update_slideshow"
    end
    member do
      get "show_full_size"
    end
  end
  
   
   get '404', :to => 'application#page_not_found'
   get '422', :to => 'application#server_error'
   get '500', :to => 'application#server_error'
  

  

  

end

app/views/layouts/_admin_nav_bar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
    <ul class="nav navbar-nav">
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        	Manage Photos <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li>
          	<%= link_to "Collections", collections_path%>
          </li>
          <li>
          	<%= link_to "Photos - Master list", photos_path%>
          </li>
      		
      		<li><%=link_to "Manage Slideshow", manage_slideshow_photos_path %></li>    
        </ul>
      </li>
      
      <li class="dropdown">
      	<a href="#" class="dropdown-toggle" data-toggle="dropdown">
        	Prints <b class="caret"></b>
        </a>
      	 <ul class="dropdown-menu">
          <li>
          	<%=link_to "Print Types", print_types_path%>
          </li>
          <li>
          	<%=link_to "Print Options", print_options_path%>
          </li>
      		
      		
        </ul>
      	
      
      </li>
      <li><%=link_to "Customer Orders", customer_orders_path %></li>
       <li><%=link_to "Discount Codes", discount_codes_path %></li>
      
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
        	Site Content <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li>
          	<%=link_to "HTML Content", edit_additional_content_path(AdditionalContent.first) if AdditionalContent.first.present? %>
          </li>
          <li>
          	<%= link_to "Site Photos", site_photos_path%>
          </li>
        </ul>
      </li>
    </ul>
    
    <ul class="nav navbar-nav navbar-right">
      
      <li>
      	<%= link_to("#{current_admin.email} sign out", destroy_admin_session_path, :method => :delete) if admin_signed_in? %>
      </li>
     
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Twitter Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "danger" %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_shopping_cart.html.erb
<div id="shopping_cart_link_container" class="pull-right">
	
	
	
	<% if session[:shopping_cart_id].present? %>
		<span class="glyphicon glyphicon-shopping-cart"></span>
		<%= link_to "Shopping Cart", shopping_cart_path  %>
	<%end%>
	
	<%= facebook_share_button %>
	
</div>		

app/views/layouts/_sidebar.html.erb
<!-- Sidebar -->
      <div id="sidebar-wrapper">
        <ul class="sidebar-nav">
	    	<li class="sidebar-brand">
	          	<%= link_to root_url, class:"" do%>	
					<%= image_tag SitePhoto.find_by_name("site_logo").photo_file.url(:original), width: "220"%>
				<%end%>
         	</li>
	         
	         <% Collection.all.each do |collection|%>
				<li>	
					<%= link_to collection.name,  collection %>
				</li>	
			<%end%>	
			
			<li>
				<%= link_to "Print Details",  page_path('print_details')%>
			</li>			  
        	<li>
				<div class="text-info free-shipping">
					<div class="horz-padding">Free ground shipping</div>
					<div class="horz-padding">on all orders.</div>
		        </div>
			</li>
        	
        	
        	<li class="top-buffer-big">
				<%= link_to "Philosophy", page_path('philosophy')%>
			</li>
			<li>
				<%= link_to "Travel Quotes", page_path('travel_quotes') %>
			</li>
			<li>
				<%= link_to "Contact", page_path('contact') %>
			</li>
			
			
        </ul>    
      </div>

app/views/layouts/_sidebar_lg.html.erb
<ul class="nav  " id="menu-lg">          
    
    <li class="logo-image-nav">
        <%= link_to root_url, class:"logo-image-link" do%>	
			<%= image_tag 'logo.png', class:"logo-image"%>
		<%end%>
    </li>
    
    <% Collection.all.each do |collection|%>
		<li>	
			<%= link_to collection.name,  collection %>
		</li>
	<%end%>	
    <li>
		<%= link_to "Print Details",  page_path('print_details')%>
	</li>
    <li class="top-buffer-big">
		<%= link_to "Philosophy", page_path('philosophy')%>
	</li>
	<li>
		<%= link_to "Travel Quotes", page_path('travel_quotes') %>
	</li>
	<li>
		<%= link_to "Contact", page_path('contact') %>
	</li>
</ul>

app/views/layouts/_sidebar_xs.html.erb
<ul class="nav visible-xs" id="menu-xs">          
    <li class="logo-image-nav">
        <%= link_to root_url, class:"logo-image-link" do%>	
			<%= image_tag 'logo.png', class:"logo-image"%>
		<%end%>
    </li>
    
    <li class="top-buffer-big" >
		<a class="pull-left">
		<span id="show_menu" class="glyphicon glyphicon-list"></span>
		</a>
	</li>
</ul>

app/views/layouts/_top_links.html.erb
<div id="top_links_container" class="">
	<span class="text-muted  pull-left">
		Free UPS ground shipping on all orders.
	</span>
	
	
	<span class="pull-right">
		<% if session[:shopping_cart_id].present? %>
			<span class="glyphicon glyphicon-shopping-cart"></span>
			<%= link_to "Shopping Cart", shopping_cart_path  %>
		<%end%>
		
		<%= facebook_share_button %>
	</span>
</div>		

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  	<head>
	    <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1.0">
	    <title>
	    	<%= content_for?(:title) ? yield(:title) : "Beyond The Precipice - Fine Art Photography" %>
	    </title>
	    
	    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Beyond The Precipice" %>">
	    <script type="text/javascript" src="https://js.stripe.com/v2/"></script> 
	    
	    <%= stylesheet_link_tag "application", media: "all", "data-turbolinks-track" => true %>
	    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
	    <%= csrf_meta_tags %>
	    <%= favicon_link_tag 'favicon.ico' %>
	    <%= tag :meta, :name => "stripe-key", :content => Rails.configuration.stripe[:publishable_key] %>
	    
	    <meta property="og:image" content="<%= open_graph_values[:image]%>" /> 
	    <meta property="og:title" content="<%= open_graph_values[:title]%>"/>
	    <meta property="og:url" content="<%= open_graph_values[:url]%>"/>
	    <meta property="og:site_name" content="<%= open_graph_values[:site_name]%>"/>
	    <meta property="og:description" content="<%= open_graph_values[:description]%>"/>
	    <meta property="og:type" content="<%= open_graph_values[:type]%>"/>
	    
	    <meta property="og:image:type" content="<%= open_graph_values[:image_type]%>"/>
		<meta property="og:image:width" content="<%= open_graph_values[:image_width]%>"/>
		<meta property="og:image:height" content="<%= open_graph_values[:image_height]%>"/>
        <script>
		  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
		  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
		  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
		  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');
		
		  ga('create', 'UA-48350686-1', 'beyondtheprecipice.com');
		  ga('send', 'pageview');
		
		</script>
	
  	</head>
	<body data-controller="<%= controller_name %>" data-action="<%= action_name %>" data-static-page="<%= static_page_name %>">	
   		<div id="fb-root"></div>
		<script>
			window.fbAsyncInit = function() {
		        FB.init({
		          appId      : '1454658354765943',
		          status     : true,
		          xfbml      : true
		        });
		      };
		
		      (function(d, s, id){
		         var js, fjs = d.getElementsByTagName(s)[0];
		         if (d.getElementById(id)) {return;}
		         js = d.createElement(s); js.id = id;
		         js.src = "//connect.facebook.net/en_US/all.js";
		         fjs.parentNode.insertBefore(js, fjs);
		       }(document, 'script', 'facebook-jssdk'));
		</script>
   		
   		<div class="container">
   			<div class="row">
   				<!-- Sidebar -->
   				<div id="sidebar"  class="col-xs-2 fixed">
   					<%= render 'layouts/sidebar_lg'%>
   				</div>
   				<!-- End Sidebar -->
   				
   				<div id="bg-container" class="col-xs-10 col-xs-offset-2">
   					<%= set_background_image %>  	
   				</div>
   				
   				<!-- main -->
   				<div id="main" class="col-xs-10 col-xs-offset-2  ">	
   					<div class="row">
   						<div class="col-xs-11">
   							<%= render 'layouts/admin_nav_bar' if admin_signed_in?%>   							
   							<%= render 'layouts/top_links'%>
   							<%= yield %>
						</div>
   					</div>
   				</div>
   				<!-- End Main -->
   			</div>
   		</div>
  	</body>
</html>